// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: connection.int.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConnectionInt_TransferMessage_FullMethodName = "/pb.ConnectionInt/TransferMessage"
)

// ConnectionIntClient is the client API for ConnectionInt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConnectionIntClient interface {
	// 消息转发
	TransferMessage(ctx context.Context, in *TransferMessageReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type connectionIntClient struct {
	cc grpc.ClientConnInterface
}

func NewConnectionIntClient(cc grpc.ClientConnInterface) ConnectionIntClient {
	return &connectionIntClient{cc}
}

func (c *connectionIntClient) TransferMessage(ctx context.Context, in *TransferMessageReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ConnectionInt_TransferMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnectionIntServer is the server API for ConnectionInt service.
// All implementations must embed UnimplementedConnectionIntServer
// for forward compatibility.
type ConnectionIntServer interface {
	// 消息转发
	TransferMessage(context.Context, *TransferMessageReq) (*emptypb.Empty, error)
	mustEmbedUnimplementedConnectionIntServer()
}

// UnimplementedConnectionIntServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConnectionIntServer struct{}

func (UnimplementedConnectionIntServer) TransferMessage(context.Context, *TransferMessageReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferMessage not implemented")
}
func (UnimplementedConnectionIntServer) mustEmbedUnimplementedConnectionIntServer() {}
func (UnimplementedConnectionIntServer) testEmbeddedByValue()                       {}

// UnsafeConnectionIntServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConnectionIntServer will
// result in compilation errors.
type UnsafeConnectionIntServer interface {
	mustEmbedUnimplementedConnectionIntServer()
}

func RegisterConnectionIntServer(s grpc.ServiceRegistrar, srv ConnectionIntServer) {
	// If the following call pancis, it indicates UnimplementedConnectionIntServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConnectionInt_ServiceDesc, srv)
}

func _ConnectionInt_TransferMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionIntServer).TransferMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectionInt_TransferMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionIntServer).TransferMessage(ctx, req.(*TransferMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ConnectionInt_ServiceDesc is the grpc.ServiceDesc for ConnectionInt service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConnectionInt_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ConnectionInt",
	HandlerType: (*ConnectionIntServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TransferMessage",
			Handler:    _ConnectionInt_TransferMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "connection.int.proto",
}
