mysql:
  name: root
  password: 123456
  ip: 0.0.0.0
  port: 3306
  dbname: nbim
redis:
  endpoints:
    - 0.0.0.0:6379
  password: 123456
etcd:
  endpoints:
    - 0.0.0.0:2379
  timeout: 5
push_room_subscribe_num: 100
push_all_subscribe_num: 100
gateway_node_id: 1
state_cathe_slot_num: 1024

connection_local_addr: 0.0.0.0:8000
connection_tcp_addr: 0.0.0.0:8001
connection_ws_addr: 0.0.0.0:8002
connection_ipconfig_addr: 0.0.0.0:8003
connection_logic_addr: 0.0.0.0:8004
gateway_rpc_addr: 0.0.0.0:8005
state_rpc_addr: 0.0.0.0:8006
logic_rpc_addr: 0.0.0.0:8010
# logic_rpc_int_addr: 0.0.0.0:8010
# logic_rpc_ext_addr: 0.0.0.0:8010
